### ISSUE TITLE
Misunderstand `--`  as binary operator (minus), this means 1 line comment.

### ISSUE THREAD

**Issue by matsuzaki215** [matsuzaki215/sqlint#5]
## What

- Because of the title,  miss-point out whitespaces before `--` 
- Point out as below
  `1 line comment should be not "--" but "#" `

**Comment by srossross** [comment]
Is this project still active?

**Comment by matsuzaki215** [comment]
> Is this project still active?

@srossross 
Yes it is.
But, recently, I am developing to add `chrome extension` module  for formatting in BigQuery console.
So I have left batch module expadning now.

https://github.com/shigeru0215/sqlint/tree/feature/add_chrome_extension

**Comment by matsuzaki215** [comment]
Solved
